name: Build and deploy to GitHub Pages

on:
  push:
    branches: [dev, main, dima, vira, andrey, vova, michael, polina, vadim, alex, vik]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install, lint 🔧
        run: |
          npm install
          npm run lint
